### ISSUE TITLE
Wargames SHPs: Australia is mis-labeled.

### ISSUE THREAD

**Issue by stharward** [mapsam/project-linework#13]
In the Wargames SHPs, Australia is mis-labeled as "Ashmore and Cartier Islands":
![image](https://cloud.githubusercontent.com/assets/10232905/8834649/6cb8c1a6-3083-11e5-9811-d45bb0467d06.png)
These are a separate territory.

**Comment by mapsam** [comment]
Well, that is no good! @pinakographos any chance you can make that update?

**Comment by pinakographos** [comment]
Indeed. Must have been some sort of mixup with the attribute join. I'll
look at this a little later today.

**Comment by pinakographos** [comment]
Updated entry in .dbf and .json. Should be good now.
