### ISSUE TITLE
Hey maybe add an icon in the header for contact info?

### ISSUE THREAD

**Issue by pinakographos** [mapsam/project-linework#23]
There are little icons there for a couple of other things. Maybe one also for contact info. I've got it listed in the "About" page, but something more upfront might be handy, too.

Like… [email icon]: Daniel Huffman, somethingaboutmaps@gmail.com

Also: we should get you some credit on the page somewhere, too! If you want to list yourself in the email contact as well, go ahead (if you want random people writing in to you about lineworky things), or if you'd like not to be responsible for handling that sort of stuff and want something on the bottom of the page like a "site power by Vance Matthews being cool" sort of thing.

**Comment by mapsam** [comment]
Good idea! Take a look at pull request #23

I'm feeling quite pleased with attribution already since things are attached to my Github account. Thanks for the thought, @pinakographos!

**Comment by pinakographos** [comment]
Done and closed!
