### ISSUE TITLE
New TopoJSONSs for Moriarty Hand small scale

### ISSUE THREAD

**Issue by pinakographos** [mapsam/project-linework#26]
TopoJSON doesn't like it when you have a mutlipart feature that crosses 180º longitude. I have generated new GeoJSONs which break these into singlepart features, and can be used to generate new TopoJSONs. Have sent them to @mapsam via email.

The current GeoJSON files in the repo are fine (GeoJSON handles the 180º crossing fine). Just using them only to make the new TopoJSONs, not replace current GeoJSONs.

**Comment by pinakographos** [comment]
Update: I think we tried this several months ago and it didn't work. I was hoping to ignore this problem until it went away.

**Comment by mapsam** [comment]
Same ^

**Comment by pinakographos** [comment]
Here's a thought: what if we didn't ship TopoJSON with each of these? I feel like, if we have GeoJSON and .shp, we've got pretty much everyones needs covered, right? TopoJSON seems like the most fraught with difficulty of our formants, since we have to worry about things like crossing 180º and that detail parameter that we have to crank up well past the default (I don't remember what it's called, but the one that controls how fine the grid is).

**Comment by mapsam** [comment]
I don't see a reason to remove the topojsons that already exist, but it seems like a good idea to not promise TopoJSON for moriarty hand unless I can get it working. I'll update the site right now to reflect this.

**Comment by mapsam** [comment]
Updated the site, going to close this and keep it a final solution until someone needs em.
