### ISSUE TITLE
Default Share Image for Social

### ISSUE THREAD

**Issue by jonno-norton** [mapsam/project-linework#27]
Really cool project, great art and interesting content. I was trying to share to my Facebook and it didn't populate an image. You can fix this with a simple line of code in your <head> I'll post it below:

meta property="og:image" content="YOUR IMG URL HERE.png"
meta property="og:url" content="YOUR SHARE URL HERE.com"
meta property="og:title" content="YOUR POST TITLE HERE"

That should get you a post with a title, share URL and image when it goes to Facebook. I'm not positive if that code will affect other social networks as well.

**Comment by mapsam** [comment]
Thanks for pointing this out, @jonno-norton! 

Pushed those changes up and looks like we are all set.

<img width="951" alt="screen shot 2015-11-08 at 5 28 49 pm" src="https://cloud.githubusercontent.com/assets/1943001/11023142/3b32c3c8-863e-11e5-89ba-10a1ba77f91f.png">
