### ISSUE TITLE
No Ukraine in 1981

### ISSUE THREAD

**Issue by JonathanWolff99** [mapsam/project-linework#39]
Hello, in the 1981 map Ukraine is missing (as well as Liechtenstein). That may cause you some issues with angry Ukrainians or USSR nostalgics...
Nice maps anyway, thank you for sharing them

**Comment by mapsam** [comment]
cc @pinakographos who is the author of this set!

**Comment by pinakographos** [comment]
@JonathanWolff99 Thanks for pointing this out! Edits are in progress for Ukraine. Liechtenstein, however, is tiny enough that I'm going to leave it be for now (likewise the Vatican and San Marino).

**Comment by mapsam** [comment]
Thanks @pinakographos! New linework set has been uploaded and is available for download at https://giscollective.s3.amazonaws.com/projectlinework/1981-v1.1.zip
